version: '3.5'

services:
  # attacker, x-terminal and trusted-server are in the same network
  xterminal:
    build:
      context: .
      target: xterminal
    container_name: x-terminal
    hostname: x-terminal
    networks:
      my-network:
        ipv4_address: 172.28.1.2
    cap_add:
      - NET_ADMIN

  trusted-server:
    build:
      context: .
      target: trusted-server
    container_name: trusted-server
    hostname: trusted-server
    networks:
      my-network:
        ipv4_address: 172.28.1.3
    cap_add:
      - NET_ADMIN

  attacker:
    build:
      context: .
      target: attacker
    container_name: attacker
    hostname: attacker
    networks:
      my-network:
        ipv4_address: 172.28.1.4
    cap_add:
      - NET_ADMIN

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
