version: '3.5'

services:
  # attacker, x-terminal and trusted-server are in the same network
  xterminal:
    build: ./xterminal
    container_name: x-terminal
    hostname: x-terminal
    networks:
      my-network:
        ipv4_address: 172.28.1.2

  trusted-server:
    build: ./trusted-server
    container_name: trusted-server
    hostname: trusted-server
    volumes:
      - ./trusted-server/login.sh:/login.sh
    networks:
      my-network:
        ipv4_address: 172.28.1.3
    cap_add:
      - NET_ADMIN

  attacker:
    build: ./attacker
    container_name: attacker
    hostname: attacker
    volumes:
      - ./attacker/scripts/:/scripts/
    networks:
      my-network:
        ipv4_address: 172.28.1.4

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24
